name: Deploy String Analyzer API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test API endpoints
      run: |
        # Start the API in background
        uvicorn main:api --host 0.0.0.0 --port 8000 &
        sleep 5
        
        # Test health check
        curl -f http://localhost:8000/docs || exit 1
        
        # Test create string
        curl -X POST "http://localhost:8000/strings" \
             -H "Content-Type: application/json" \
             -d '{"value": "test"}' || exit 1
        
        # Test get strings
        curl -f "http://localhost:8000/strings" || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/string-analyzer-api
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart string-analyzer
          sudo systemctl restart nginx